name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write # for creating releases
      issues: write # for commenting on issues
      pull-requests: write # for commenting on PRs

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      # Setup Node.js & Bun
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: latest

      # Install Dependencies
      - name: Install dependencies
        run: bun install

      # Semantic Release
      - name: Create Release
        uses: cycjimmy/semantic-release-action@v6.0.0
        with:
          semantic_version: 25
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
